# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v5.3.3
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: es_AR
odoo_listdb: true
odoo_oci_image: ""
odoo_proxy: other
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Nimarosa
project_license: no_license
project_name: odoo16-dev
smtp_default_from: ""
smtp_relay_host: ""
